trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  webProject: 'src/BudgetTracker.WebApi/BudgetTracker.WebApi.csproj'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.x'

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: 'BudgetTracker.sln'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: 'BudgetTracker.sln'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: 'Test/Test.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build'

- task: DotNetCoreCLI@2
  displayName: Publish WebApi
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(webProject)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish'
    zipAfterPublish: true

- task: AzureWebApp@1
  displayName: Deploy to App Service
  inputs:
    azureSubscription: 'NOME_DA_SERVICE_CONNECTION'
    appType: 'webApp'
    appName: 'budgettracker-api'
    package: '$(Build.ArtifactStagingDirectory)/publish/**/*.zip'